# Quick-Flow: Create Tech-Spec
name: create-tech-spec
description: "Conversational spec engineering - ask questions, investigate code, produce implementation-ready tech-spec."
author: "SAGE"

# Config
config_source: "{project-root}/sage/core/config.yaml"
output_folder: "{config_source}:output_folder"
sprint_artifacts: "{config_source}:sprint_artifacts"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/sage/workflows/software/quick-flow/create-tech-spec"
instructions: "{installed_path}/instructions.md"

# Related workflows
quick_dev_workflow: "{project-root}/sage/workflows/software/quick-flow/quick-dev/workflow.yaml"
party_mode_exec: "{project-root}/sage/core/workflows/party-mode/workflow.md"
advanced_elicitation: "{project-root}/sage/core/tasks/advanced-elicitation.xml"

standalone: true