# Run Epic Orchestrated - Software Module
# Version: 1.0
#
# This workflow executes an entire epic using phased execution with persistent state.
# Each phase is a separate file, orchestrated by a thin loop that manages state.
#
# Software-specific features:
# - TDD enforcement in implementation phase
# - Mandatory smoke tests in QA phase
# - Branch naming validation: feature/{story-id}
# - Learning recorder integration for failure analysis

name: "run-epic"
version: "1.0-phased"
description: "Execute epic with phased architecture - TDD, bounded context, resumable, visible progress"

# Core components integration
components:
  - "sage/core/components/state-manager.md"
  - "sage/core/components/retry-handler.md"
  - "sage/core/components/metrics-collector.md"
  - "sage/core/components/learning-recorder.md"
  - "sage/core/components/subagent-spawner.md"

# Entry point - the orchestrator manages all phase transitions
entry: "orchestrator.md"

# State management
state:
  schema: "state-schema.json"
  location: "state/epic-{epic_id}-state.json"
  persist: true  # Write state after each phase

# Phase definitions (execution order managed by orchestrator)
phases:
  - id: "00-init"
    file: "phases/00-init.md"
    description: "Parse epic, build story queue, create epic branch"

  - id: "01-story-start"
    file: "phases/01-story-start.md"
    description: "Load next story, create feature/{story-id} branch, update status"

  - id: "02-plan"
    file: "phases/02-plan.md"
    description: "Spawn PLANNER subagent to decompose story into chunks"
    subagent: true

  - id: "03-implement"
    file: "phases/03-implement.md"
    description: "Spawn IMPLEMENTER subagent for one chunk with TDD"
    subagent: true
    loops: true  # This phase loops until all chunks done

  - id: "04-test"
    file: "phases/04-test.md"
    description: "Run tests, spawn FIXER subagent if failures"
    subagent: true
    retries: 3

  - id: "05-review"
    file: "phases/05-review.md"
    description: "Spawn REVIEWER subagent for adversarial code review"
    subagent: true
    retries: 2

  - id: "06-story-complete"
    file: "phases/06-story-complete.md"
    description: "Update story status, merge to epic branch"

  - id: "07-epic-qa"
    file: "phases/07-epic-qa.md"
    description: "Mandatory smoke test, optional regression"
    mandatory: true

  - id: "08-finalize"
    file: "phases/08-finalize.md"
    description: "Generate metrics, learning summary, human checkpoint"

# Subagents used by phases
subagents:
  planner:
    type: "general-purpose"
    purpose: "Decompose story into implementable chunks"
    phase: "02-plan"
    context_limit: "4KB"

  implementer:
    type: "general-purpose"
    purpose: "Implement one chunk with TDD (test-first)"
    phase: "03-implement"
    context_limit: "4KB"

  fixer:
    type: "general-purpose"
    purpose: "Diagnose and fix test failures"
    phase: "04-test"
    context_limit: "4KB"

  reviewer:
    type: "general-purpose"
    purpose: "Adversarial code review"
    phase: "05-review"
    context_limit: "4KB"

  tester:
    type: "general-purpose"
    purpose: "Run smoke and regression tests"
    phase: "07-epic-qa"
    context_limit: "4KB"

# Git branching strategy
git:
  epic_branch: "epic-{epic_id}"
  story_branch: "feature/{story_id}"  # Software uses feature/ prefix
  base: "dev"

# Retry configuration (from core retry-handler)
retry:
  test: 3       # Test failures
  review: 2     # Review iterations
  build: 1      # Build failures (usually deterministic)

# Cascade detection
cascade:
  threshold: 3           # Failures in window
  window: 5              # Stories
  action: "pause_and_diagnose"

# Metrics output
metrics:
  output: "docs/sprint-artifacts/epic-{epic_id}-metrics.json"

# Learning integration
learning:
  output: "docs/sprint-artifacts/learning/"
  aggregate_on_complete: true

# Version history
changelog:
  - version: "1.0"
    date: "2025-12-19"
    changes:
      - "Initial software module orchestrator"
      - "Adapted from game/run-epic-orchestrated v3.0"
      - "TDD enforcement in implementation phase"
      - "Mandatory smoke tests (phase 07)"
      - "Learning recorder integration"
      - "Core components integration"
