# Epic Completion Workflow
name: "epic-complete"
description: "Verify an epic is ready for completion by checking all stories are done, playtest is complete, and no blocking bugs remain. Updates epic status to complete."
author: "SAGE"

config_source: "{project-root}/sage/core/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"

installed_path: "{project-root}/sage/workflows/game/production/epic-complete"
template: false
instructions: "{installed_path}/instructions.md"

# Required inputs
required_inputs:
  - agent_manifest: "{project-root}/sage/data/agent-manifest.csv"

# Input file patterns
input_file_patterns:
  epics:
    description: "Epic with user stories"
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
    load_strategy: "SELECTIVE_LOAD"

# Required files
sprint_status_file: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"
story_directory: "{sprint_artifacts}"
playtest_folder: "{sprint_artifacts}"
bugs_folder: "{sprint_artifacts}/bugs"

# Related workflows
playtest_workflow: "{project-root}/sage/workflows/game/production/epic-playtest"
retrospective_workflow: "{project-root}/sage/workflows/game/production/retrospective"

standalone: true
web_bundle: false
