# Game Brief - Interactive Workflow Configuration
name: game-brief
description: "Interactive game brief creation workflow that guides users through defining their game vision with multiple input sources and conversational collaboration"
author: "SAGE"

# Critical variables from config
config_source: "{project-root}/sage/core/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Module path and component files
installed_path: "{project-root}/sage/workflows/game/preproduction/game-brief"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/game-brief-{{game_name}}-{{date}}.md"

standalone: true

web_bundle:
  name: "game-brief"
  description: "Interactive game brief creation workflow that guides users through defining their game vision with multiple input sources and conversational collaboration"
  author: "SAGE"
  instructions: "sage/workflows/game/preproduction/game-brief/instructions.md"
  validation: "sage/workflows/game/preproduction/game-brief/checklist.md"
  template: "sage/workflows/game/preproduction/game-brief/template.md"
  web_bundle_files:
    - "sage/workflows/game/preproduction/game-brief/instructions.md"
    - "sage/workflows/game/preproduction/game-brief/checklist.md"
    - "sage/workflows/game/preproduction/game-brief/template.md"
