# Create Epic - Core Workflow (Module-Agnostic)
# Version: 2.0
#
# This is the core create-epic workflow that can be extended by game/ and software/ modules.
# It provides shared logic for epic setup with retrospective learning integration.

name: create-epic
description: "Orchestrate complete epic setup: review retros, analyze dependencies, create all stories with full context injection, generate story contexts, and produce epic kickoff summary"
author: "SAGE Framework"
version: "2.0"

# Critical variables from config
config_source: "{project-root}/sage/core/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"

# Workflow components
installed_path: "{project-root}/sage/workflows/core/epic/create-epic"
instructions: "{installed_path}/instructions.md"
briefing_template: "{installed_path}/templates/briefing-template.md"
# Note: story_template not needed - stories created via story creation workflow

# Core components integration (EPIC-002)
components:
  - "sage/core/components/state-manager.md"
  - "sage/core/components/metrics-collector.md"
  - "sage/core/components/learning-recorder.md"

# State management
state:
  schema: "state-schema.json"
  location: ".sage/state/create-epic-{epic_id}-state.json"
  persist: true

# Input variables
variables:
  # Target epic (required - will be elicited if not provided)
  epic_identifier: "" # e.g., "8", "mini-sprint-uiux", "epic-8"

  # Sprint tracking
  sprint_status_file: "{sprint_artifacts}/sprint-status.yaml"

  # Retrospective sources (glob pattern for all retros)
  retrospectives_pattern: "{sprint_artifacts}/epic-*-retro-*.md"

  # Epic definition sources (module-specific, can be overridden)
  epics_file: "{output_folder}/epics.md"
  epic_definitions: "{output_folder}/*epic*.md"

  # Architecture and tech context
  architecture_file: "{output_folder}/architecture.md"
  tech_spec_pattern: "{output_folder}/tech-spec-*.md"
  patterns_dir: "{output_folder}/patterns"

  # Output locations
  briefing_output: "{sprint_artifacts}/{{epic_key}}-briefing.md"

# Smart input file references
input_file_patterns:
  # EPIC-002: Read epic state files for learning_records and retro_notes
  epic_state_files:
    description: "Epic state files with learning records from previous epics"
    pattern: ".sage/state/epic-*-state.json"
    load_strategy: "FULL_LOAD"

  retrospectives:
    description: "All previous retrospectives for learning extraction"
    pattern: "{sprint_artifacts}/epic-*-retro-*.md"
    load_strategy: "FULL_LOAD"

  patterns_registry:
    description: "Technical patterns for injection"
    whole: "{output_folder}/patterns/*.md"
    load_strategy: "FULL_LOAD"

  architecture:
    description: "System architecture"
    whole: "{output_folder}/*architecture*.md"
    load_strategy: "FULL_LOAD"

  epics:
    description: "Epic breakdown document"
    whole: "{epic_definitions}"
    load_strategy: "SELECTIVE_LOAD"

# Workflow outputs
outputs:
  epic_briefing: "{briefing_output}"
  dependency_analysis: "{sprint_artifacts}/{{epic_key}}-dependencies.yaml"
  kickoff_summary: "{sprint_artifacts}/{{epic_key}}-kickoff.md"

# Workflow phases (for documentation - actual logic in instructions.md)
phases:
  phase_1:
    name: "Retrospective Review & Epic Validation"
    description: "Load all retros + state files, extract learnings, validate epic stories against patterns"
    outputs:
      - epic_briefing_document
      - applicable_patterns_list
      - action_items_to_address
      - learning_records_extracted

  phase_2:
    name: "Dependency Analysis"
    description: "Analyze story dependencies, determine parallel vs sequential execution"
    outputs:
      - execution_batches
      - dependency_graph
      - batch_rationale

  phase_3:
    name: "Story Draft Creation"
    description: "Spawn subagents to create story drafts in batch order"
    outputs:
      - story_files_created
      - creation_status_per_story

  phase_4:
    name: "Story Context Generation"
    description: "Spawn subagents to generate story contexts in batch order"
    outputs:
      - context_files_created
      - stories_ready_for_dev

  phase_4_5:
    name: "Verify All Stories Ready for Dev"
    description: "Ensure no stories are left in drafted/backlog state - mark ready-for-dev if context was skipped"
    outputs:
      - verification_report
      - stories_promoted_without_context

  phase_5:
    name: "Epic Kickoff Summary"
    description: "Generate summary, update sprint-status, provide execution guidance"
    outputs:
      - kickoff_summary_document
      - sprint_status_updated
      - dev_execution_order

# Subagent configuration
subagent_config:
  type: "scrum-master"
  model: "sonnet" # Use sonnet for subagents (faster, sufficient for story creation)
  timeout: 300000 # 5 minutes per story

# Tell Don't Ask - Context injection structure
context_injection:
  epic_briefing:
    - retro_learnings
    - state_file_learnings  # NEW: learning_records from state files
    - applicable_patterns
    - technical_context
    - story_dependencies
  per_story:
    - story_definition
    - specific_patterns
    - architecture_excerpts
    - predecessor_learnings

# Extension points for modules
extension_points:
  # Modules can override these to customize behavior
  epic_definition_source: "Override to specify module-specific epic source (e.g., GDD.md for game)"
  story_workflow: "Override to specify module-specific create-story workflow"
  context_workflow: "Override to specify module-specific story-context workflow"
  pattern_matching: "Override to add module-specific pattern matching logic"

standalone: true
web_bundle: false

# Version history
changelog:
  - version: "2.0"
    date: "2024-12-24"
    changes:
      - "EPIC-002: Core components integration (state-manager, metrics-collector, learning-recorder)"
      - "STORY-2-2: State file reading for learning_records and retro_notes"
      - "STORY-2-2: Unified core workflow with module extension points"
      - "STORY-2-2: Assistant agent integration support"
      - "Module-agnostic: Extracted shared logic from game/create-epic"
      - "Extension points defined for game/ and software/ modules"

  - version: "1.0"
    date: "2024-11-XX"
    changes:
      - "Initial release (game-specific only)"
      - "Retrospective review and pattern injection"
      - "Dependency analysis and batching"
      - "Subagent-based story creation"
