# Narrative Design Workflow
name: narrative
description: "Narrative design workflow for story-driven games and applications. Creates comprehensive narrative documentation including story structure, character arcs, dialogue systems, and narrative implementation guidance."
author: "SAGE"

# Critical variables from config
config_source: "{project-root}/sage/core/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Workflow components
installed_path: "{project-root}/sage/workflows/game/design/narrative"
instructions: "{installed_path}/instructions-narrative.md"
template: "{installed_path}/narrative-template.md"

# Output configuration
default_output_file: "{output_folder}/narrative-design.md"

standalone: true

web_bundle:
  name: "narrative"
  description: "Narrative design workflow for story-driven games and applications. Creates comprehensive narrative documentation including story structure, character arcs, dialogue systems, and narrative implementation guidance."
  author: "SAGE"
  instructions: "sage/workflows/game/design/narrative/instructions-narrative.md"
  web_bundle_files:
    - "sage/workflows/game/design/narrative/instructions-narrative.md"
    - "sage/workflows/game/design/narrative/narrative-template.md"
